### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by ink8bit** [ink8bit/web-app-boilerplate#59]
# CI 
Add following CI support:
- travis:
```yaml
language: node_js
node_js:
  -"8"
```
- appveyor:
```yaml
environment:
  matrix:
    - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
```
